version: '3.9'

services:
  app:
    build: .
    volumes:
      - ./pkg:/go/jato/pkg:cached
      - ./test:/go/jato/test:cached
    environment: 
      - "JATO_SSH_USER=${JATO_SSH_USER}"
      - "JATO_SSH_PASS=${JATO_SSH_PASS}"
