version: '3.9'

services:
  app:
    build: .
    volumes:
      - ./ssh:/go/jato/ssh:cached
      - ./telnet:/go/jato/telnet:cached
      - ./test:/go/jato/test:cached
      - ./jato.go:/go/jato/jato.go:cached
    environment: 
      - "JATO_SSH_USER=${JATO_SSH_USER}"
      - "JATO_SSH_PASS=${JATO_SSH_PASS}"
